### ISSUE TITLE
core panik when sending a led behavior change when ap mode

### ISSUE THREAD

**Issue by AGlElectronics** [AGL-Electronics/Lumin-Desktop#12]
log attached line 2750 there about i gave command to change (not shown in log but easy to replicate)
[device-monitor-240420-142750.log](https://github.com/AGL-Electronics/Lumin-Desktop/files/15048201/device-monitor-240420-142750.log)

**Comment by ZanzyTHEbar** [comment]
Since we know this is an issue with the HSPI bus usage of the w5500, should we change the issue to a hardware one?

**Comment by roscog** [comment]
Probably yep

**Comment by roscog** [comment]
Send to lumin and fixed in v1.3.1
