### ISSUE TITLE
Cancel does not work after configuration error

### ISSUE THREAD

**Issue by madnotna** [AGL-Electronics/Lumin-Desktop#9]
When making a configuration error (ethernet instead of WiFi) the app tries to connect to the Lumin after the save button but will get an error. The Cancel option does not work.
Closing and restarting the app does not solve this.
After restarting you will get a black screen where the config options are.

![image](https://github.com/AGL-Electronics/Lumin-Desktop/assets/66881194/1c297ca3-bf5b-49a4-9725-ecd863fcb823)

Remove and reinstall the app does not solve this.

**Comment by madnotna** [comment]
Solved, removing appdata in %appdata% com.aglelectronics.dev solved this black screen.

**Comment by ZanzyTHEbar** [comment]
The app is still in _very early_ alpha. These issues are known - and will be solved as we become more robust. Thank you for making an issue :) 

For future reference, if anything weird seems to happen please press `ctrl+f5` while focued on the app. This will remove all app caches and force the app to refresh the ui.

**Comment by madnotna** [comment]
Alan ask me to report it on GitHub as I’m one of the (early) beta testers and I have very short lines with Alan. Where do you think I got this beta version as it is not on GitHub?
